name: CI

on:
  push:
    branches: [ main, initial ]
  pull_request:
    branches: [ main, initial ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint (ruff) and format (black --check)
        run: |
          ruff check .
          black --check .
      - name: Type check (mypy)
        run: |
          mypy src || true
      - name: Build Rust crate (no inference)
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config
          rustup toolchain install stable
          rustup default stable
          cargo build --manifest-path rust/morphology_runtime/Cargo.toml
      - name: Build Rust crate (with inference)
        run: |
          cargo build --manifest-path rust/morphology_runtime/Cargo.toml --features inference
      - name: Export ONNX and run parity
        run: |
          make splits build-tagset
          python scripts/onnx_parity.py || true


