name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to upload (e.g. v0.1.1)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Resolve version
        id: v
        run: |
          if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref_type }}" == tag ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.v.outputs.tag }}
          name: ${{ steps.v.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            release_artifacts/${{ steps.v.outputs.tag#v }}/gaeilge-morph-${{ steps.v.outputs.tag#v }}.tar.gz
            release_artifacts/${{ steps.v.outputs.tag#v }}/gaeilge-morph-${{ steps.v.outputs.tag#v }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


